sudo: required
language: generic

services:
  - docker

git:
  depth: 3

env:
  - PROFILE=.profile VIM=vim    TAG=latest
  - PROFILE=.profile VIM=vim    TAG=v8.0.0000
  - PROFILE=.profile VIM=vim    TAG=v8.0.0027
  - PROFILE=.profile VIM=vim    TAG=v8.0.0107
  - PROFILE=.profile VIM=vim    TAG=v8.1.0000
  - PROFILE=.profile VIM=neovim TAG=latest
  - PROFILE=.profile VIM=neovim TAG=v0.2.0
  - PROFILE=.profile VIM=neovim TAG=v0.2.1
  - PROFILE=.profile VIM=neovim TAG=v0.2.2


addons:
  apt:
    packages:
      - docker-ce
      - python3
      - python3-pip

install:
  - pip3 install --user setuptools --upgrade
  - pip3 install --user vim-vint
  - pip3 install --user coverage covimerage
  - docker --version
  - docker build -t lambdalisue/${VIM}-themis/whiskey:${TAG} --build-arg TAG=${TAG} -f .ci/Dockerfile.${VIM} .

before_script:
  - uname -a
  - python3 --version
  - vint --version
  - docker run --rm -it lambdalisue/${VIM}-ci:${TAG} --version
  - docker run --rm -it lambdalisue/${VIM}-themis/whiskey:${TAG} --version

script:
  - vint autoload/
  - docker run --rm --volume ${PWD}:/mnt/volume -e "PROFILE=${PROFILE}" -it lambdalisue/${VIM}-themis/whiskey:${TAG}
  - docker run --rm --volume ${PWD}:/mnt/volume -it lambdalisue/${VIM}-ci:${TAG} --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit

after_success:
  - covimerage write_coverage $PROFILE
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
